# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.IntegerField(choices=[(b'0', b'click'), (b'2', b'contextmenu'), (b'1', b'dblclick'), (b'5', b'keydown'), (b'7', b'keypress'), (b'6', b'keyup'), (b'3', b'mousedown'), (b'8', b'mousemove'), (b'4', b'mouseup')])),
                ('key', models.CharField(max_length=128)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenWidth', models.IntegerField()),
                ('screenHeight', models.IntegerField()),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=b'9ca89c8b-ebdd-48ba-9fd9-3720dc0194be', max_length=36, primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, max_length=64)),
                ('baseUrl', models.URLField()),
                ('isActive', models.BooleanField(default=True)),
                ('isProcessed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='recording.Session'),
        ),
        migrations.AddField(
            model_name='actionevent',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionEvents', to='recording.Page'),
        ),
    ]
