# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=b'e41879fb-0719-42fd-86e1-a665bab5077a', max_length=36, primary_key=True, serialize=False),
        ),
    ]
