# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0002_auto_20170728_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionevent',
            name='key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='actionevent',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actionevent',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=b'5e0210ab-fc92-4520-9e45-1695d77e3f4c', max_length=36, primary_key=True, serialize=False),
        ),
    ]
