# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0003_auto_20170728_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='filename',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=b'ff06a901-c19a-4bfc-b623-2528b38132b4', max_length=36, primary_key=True, serialize=False),
        ),
    ]
