# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0004_auto_20170728_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='filename',
        ),
        migrations.AddField(
            model_name='actionevent',
            name='target',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=b'802b27e8-868e-47e8-a6ca-07734408a964', max_length=36, primary_key=True, serialize=False),
        ),
    ]
