# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0005_auto_20170802_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertedOrDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=1024)),
                ('isInserted', models.BooleanField(default=True)),
                ('innerHTML', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertedOrDeleteds', to='recording.Page')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ModifiedAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=1024)),
                ('attributeName', models.CharField(max_length=128)),
                ('oldValue', models.CharField(max_length=1024)),
                ('newValue', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiedAttributes', to='recording.Page')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=b'51169a43-4dd0-41ce-a297-cae053b04e0e', max_length=36, primary_key=True, serialize=False),
        ),
    ]
